### ISSUE TITLE
Can't use Date as a Data type

### ISSUE THREAD

**Issue by MuddyBootsCode** [neo4j-graphql/neo4j-graphql-js#134]
I'm trying to add dates to my schema. The Augmented Schema Gives me an error saying that date is not recognized as a data type. I'm currently using Strings as a work around.

**Comment by albert-the-creator** [comment]
Did you create a custom Date scalar? https://www.apollographql.com/docs/graphql-tools/scalars.html

**Comment by MuddyBootsCode** [comment]
I have not yet, hoping to get to it soon.

**Comment by mmmoli** [comment]
@albert-the-creator Any examples anywhere we can look at?

**Comment by BrenoMazieiro** [comment]
Same here:

mutation {
  CreateSomething(
    date: {
      year: 2019
      month: 2
      day: 1
      hour: 0
      minute: 0
      second: 0
    }
  )
  {
    date {
      year
      month
      day
    }
  }
}


type Something {
  date: DateTime!
}

CreateSomething (
    date: DateTime
  ): Something
    @cypher(
        statement: 
        "CREATE (s:Something \
            { \
                ID: apoc.create.uuid(), \
                date: datetime($date), \
            }) \
            Return s"
    )


"Failed to invoke procedure `apoc.cypher.doIt`: Caused by: java.lang.IllegalArgumentException: year must be an integer value, but was a DoubleValue",


DateTime is a scalar from

import {
  DateTime
} from '@okgrow/graphql-scalars'

**Comment by BrenoMazieiro** [comment]
Ive got the same

``mutation {
  CreateSomething(
    date: {
      year: 2019
      month: 2
      day: 1
      hour: 0
      minute: 0
      second: 0
    }
  )
  {
    date {
      year
      month
      day
    }
  }
}``


``type Something {
  date: DateTime!
}``

``CreateSomething (
    date: DateTime
  ): Something
    @cypher(
        statement: 
        "CREATE (s:Something \
            { \
                ID: apoc.create.uuid(), \
                date: datetime($date), \
            }) \
            Return s"
    )``


"Failed to invoke procedure `apoc.cypher.doIt`: Caused by: java.lang.IllegalArgumentException: year must be an integer value, but was a DoubleValue",


DateTime is a scalar from

``import {
  DateTime
} from '@okgrow/graphql-scalars'``

**Comment by johnymontana** [comment]
@BrenoMazieiro There's no need to use `DateTime` from graphql-scalars. `Date`, `DateTime`, and `LocalDateTime` are added to the typedefs automatically and are consistent with the Neo4j temporal types. See https://grandstack.io/docs/neo4j-graphql-js.html#temporal-types-datetime

**Comment by BrenoMazieiro** [comment]
Still the same

``
mutation {
  CreateSomething(
    date: {
      year: 2019
      month: 1
      day: 1
    }
  )
  {
    ID
    date {
      formatted
    }
  }
}
``

``type Something {
  ID: String
  date: Date!
}``

``type _Neo4jDateInput {
  year: Int
  month: Int
  day: Int
  formatted: String
}``

``CreateSomething (
    date: _Neo4jDateInput!
  ): Something
    @cypher(
        statement: 
        "CREATE (s:Something \
            {\
                ID: apoc.create.uuid(), \
                date: datetime($date), \
            }) \
            Return s"
    )
  `
``


"errors": [
    {
      "message": "Failed to invoke procedure `apoc.cypher.doIt`: Caused by: java.lang.IllegalArgumentException: year must be an integer value, but was a DoubleValue",

**Comment by BrenoMazieiro** [comment]
I'm with auto disabled.


``export const schema = makeAugmentedSchema({
  typeDefs,
  resolvers,
  schemaDirectives,
  /** turning auto-creation off */
  config: {
    query: false, 
    mutation: false
  }
})
``

**Comment by MuddyBootsCode** [comment]
This is fixed for me.

**Comment by johnymontana** [comment]
Fixed by the GraphQL temporal field functionality described in [the docs here.](https://grandstack.io/docs/graphql-temporal-types-datetime.html)

Please open a new issue if that feature does not address your use case.

**Comment by teenkevo** [comment]
> This is fixed for me.

How did you fix it @MuddyBootsCode. Am still facing the same problem

**Comment by teenkevo** [comment]
> Still the same
> 
> `mutation { CreateSomething( date: { year: 2019 month: 1 day: 1 } ) { ID date { formatted } } }`
> 
> `type Something { ID: String date: Date! }`
> 
> `type _Neo4jDateInput { year: Int month: Int day: Int formatted: String }`
> 
> `` CreateSomething ( date: _Neo4jDateInput! ): Something @cypher( statement: "CREATE (s:Something \ {\ ID: apoc.create.uuid(), \ date: datetime($date), \ }) \ Return s" ) ` ``
> 
> "errors": [
> {
> "message": "Failed to invoke procedure `apoc.cypher.doIt`: Caused by: java.lang.IllegalArgumentException: year must be an integer value, but was a DoubleValue",

@BrenoMazieiro did you manage to fix this. Please help
